lhc.api.host=localhost
lhc.api.port=2023
quarkus.devservices.enabled=false

quarkus.log.category."io.littlehorse.agent".level=DEBUG
quarkus.log.console.json.enabled=false

agent.task.name=text-to-text-agent
agent.task.input.type=TEXT
agent.task.output.type=TEXT

agent.chat-model.provider=openai
agent.chat-model.openai.api-key=ollama
agent.chat-model.openai.base-url=http://localhost:11434/v1
agent.chat-model.openai.model=qwen3:4b
agent.chat-model.openai.timeout=PT4M
agent.chat-model.openai.max-retries=1
