plugins {
    id "com.diffplug.spotless"
    id "io.quarkus"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
    maven {
        name = "Central Portal Snapshots"
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        content {
            includeGroup("io.littlehorse")
        }
    }
}

spotless {
    java {
        removeUnusedImports()
        palantirJavaFormat().style("AOSP")
    }
}

dependencies {

    // quarkus
    implementation enforcedPlatform("io.quarkus.platform:quarkus-bom:${quarkusVersion}")
    implementation "io.quarkus:quarkus-arc"
    implementation "io.quarkus:quarkus-hibernate-validator"
    implementation "io.quarkus:quarkus-smallrye-health"
    implementation "io.quarkus:quarkus-oidc-client"
    implementation "io.quarkus:quarkus-logging-json"

    // logs
    implementation "org.jboss.slf4j:slf4j-jboss-logmanager"

    // littlehorse
    implementation "io.littlehorse:littlehorse-quarkus:${version}", { changing = true }

    // Handlebars
    implementation "com.google.code.gson:gson"
    implementation "com.github.jknack:handlebars:${handlebarsVersion}"

    // langchain4j
    implementation enforcedPlatform("io.quarkiverse.langchain4j:quarkus-langchain4j-bom:${langchain4jVersion}")
    implementation "io.quarkiverse.langchain4j:quarkus-langchain4j-core"
    implementation "io.quarkiverse.langchain4j:quarkus-langchain4j-openai"
    implementation "io.quarkiverse.langchain4j:quarkus-langchain4j-anthropic"
    implementation "io.quarkiverse.langchain4j:quarkus-langchain4j-mcp"

    // tests
    testImplementation "io.quarkus:quarkus-junit5"
    testImplementation "io.quarkus:quarkus-junit5-mockito"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

compileJava {
    options.compilerArgs << '-parameters'
}

test {
    useJUnitPlatform()
}
