pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id "com.diffplug.spotless" version "${spotlessVersion}"
        id "io.quarkus" version "${quarkusVersion}"
    }
}

rootProject.name = 'lh-agent-connector'

file('examples').listFiles().findAll { it.isDirectory() }.each {
    include("example-${it.name}")
    project(":example-${it.name}").projectDir = it
}
