quarkus.devservices.enabled=false

# Model Configuration
agent.chat-model.provider=openai

agent.chat-model.anthropic.api-key=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
agent.chat-model.anthropic.model=claude-fable-5
agent.chat-model.anthropic.max-tokens=10000

agent.chat-model.openai.api-key=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
agent.chat-model.openai.model=gpt-5.6-sol
agent.chat-model.openai.reasoning-effort=none

# System Message
agent.system-message=You are a test assistant

# Task
agent.task.name=agent-text

# Output
#agent.task.output.type=STRUCT
#agent.task.output.struct.name=github-projects
#agent.task.output.struct.version=-1

# Input
#agent.task.input.type=STRUCT
#agent.task.input.struct.name=agent-input
#agent.user-message-template=Process this input: {{struct}}

# LittleHorse

#quarkus.keycloak.devservices.enabled=false

lhc.api.host=bootstrap.saddle.littlehorse.cloud
lhc.api.port=2023
lhc.api.protocol=TLS
lhc.tenant.id=demo
lhc.ca.cert=/Users/mateo/Desktop/Projects/LittleHorse/lh-saddle/.local/saddle-ca.crt
lhc.oauth.client.id=server-saddle-client
lhc.oauth.client.secret=7b8e2f4a1c9d0b5e3f6a2d9b4c1e8a0f
lhc.oauth.access.token.url=http://keycloak-service.littlehorse.svc.cluster.local:8000/realms/saddle/protocol/openid-connect/token

# MCPs

agent.mcp.clients.github.transport=streamable-http
agent.mcp.clients.github.url=https://api.githubcopilot.com/mcp/
agent.mcp.clients.github.auth.type=bearer
agent.mcp.clients.github.auth.token=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

agent.mcp.clients.yahoo.transport=streamable-http
agent.mcp.clients.yahoo.url=https://gateway.mcpservers.org/yahoo-finance/mcp

quarkus.oidc-client.something.grant.type=client
quarkus.oidc-client.something.credentials.client-secret.method=basic
