quarkus.devservices.enabled=false

# Local logging
quarkus.log.category."io.littlehorse.agent".level=DEBUG
quarkus.log.console.json.enabled=false

agent.chat-model.provider=openai
agent.chat-model.openai.api-key=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
agent.chat-model.openai.model=fable-5
agent.task.name=text-to-text-agent
