quarkus.devservices.enabled=false

# Local logging
quarkus.log.category."io.littlehorse.agent".level=DEBUG
quarkus.log.console.json.enabled=false

# Ollama Local Configurations
agent.chat-model.provider=openai
agent.chat-model.openai.api-key=ollama
agent.chat-model.openai.base-url=http://localhost:11434/v1
agent.chat-model.openai.model=qwen3:4b
agent.task.name=text-to-text-agent
