kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32023
        hostPort: 2023
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30080
        hostPort: 8080
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 31434
        hostPort: 11434
        listenAddress: "127.0.0.1"
        protocol: TCP
