name: pull-request
run-name: Testing branch "${{ github.head_ref }}"

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/shared-tests.yaml
